### ISSUE TITLE
chart.js && ng2-charts not installed

### ISSUE THREAD

**Issue by apoorvachikara** [siddhigate/dev-care-app#15]
There is an issue in the project when you run it for the first time. The dependencies : 

1) "chart.js": "^3.7.1",
2) "ng2-charts: : "^3.0.8"

are not a part of the package.json. 

I have made the changes and added them as a part of dependencies in the project. So, running `npm i` will be sufficient to run the project with all the dependencies. 

Once you close the PR this issue will be resolved.

**Comment by ZuberDunge** [comment]
Hey, I tried to run it on my local machine and I didn't face this issue. 
React-chartjs-2 library is being used over here. And, I've used the library in my projects as well, there's no need for other dependencies. and since the app is LIVE, I don't think there's an issue, otherwise it wouldn't have deployed.

**Comment by apoorvachikara** [comment]
I think you are right, maybe there is some issue with the version that I am using. When I freshly cloned it, it seems to work fine. Thanks though.
